travis:
  secure:
    BINSTAR_TOKEN: DL3YchZsG+YjEVqjqEf/DHJBbtQokr5GUBlaxJ+dTzvGnKmdmpwY8QjAVCvoHt10FVjpiYuoetOWMtwqmLUSBMulej6V5hupMch1R2ZXbL/RB0B5qC7hFzw6pspvhDtjHiriKpIuOFUPGuLnK7aRNP/q/GThWzmLvXa0XM5iSZLwKrI6+vzU5lIB4ADupKQO1RWpBLxwlRSlIN2Ut+zjtOaZWlIG+CGBv9TELAl7YLZpoZpGvp5ElL9GUBy6L+43ksr3e0XkZ2gbbDG+GzkxMkpk0kghQzoW0CVDYoq5tKG93gGTPovMrgQbKWJUu4LXkH4bFWGizDoNWlBwkpqqa6CYAAkyEkqhT9guXwYGlT3UlRvVCEsZnj1hRsU4cmOPgu47KLT2q9h06YokM5/q/ooocWexfTT05Gkd6PahJlbOcoccoxM7Y12XbJ39GZRRmVEvwBwWEY10ct02VN7aGo4NdbFmbNV7ihVOaWmhnMtHqaUQE20aeleFMU19EgkmDXnm5+jJHNBUAaSSTF06Dn8pcGh9ne8XZWapsCURa1kvFmgQUVLN6YeuGOLdWDFqEJAycMbJ9Oabl5L4ylJLOy1FxAgADrgVXlIU1CS2+QAmjLuF+IETp5qXFPNN8FqbIArFeXptlO31thpNritrALR/voaPww8f+9jMRp3Qit4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
