travis:
  secure:
    BINSTAR_TOKEN: qBaLt4lfBKux+JPRdDuqHJdDbcEkkFzCt+AiRfBZyZDeiaOUNoG1VwmVx3B9apbvgC81xvMlEluS/s/v80NJ33YFqb9UjSOQgsc/x+2W+JNN7ACsoZ4ae6yVRf6RnN6UBZ4Kkibk5sQ4m/Gc36mBfVVfQvHKgG2e/A6yh889J73QVb5OLlUyrVWu+lMfkIPN9d5zVyLlTuMdJrNjBNhfz5S+mkaIzCJYXnEoauA+ST3s3HTTbStLB3rE/7oLjisDWCGuLFk7Ts8OG/1ErDGoNTc63cjSsLIbp7aSWIfNk1iZcIsH9n34JDmePy/otMhRqF84QVmQHbZhofnAoB4PgTMQErnNF/TlWM3CHKM2e1/qBQgz6kqAb9f5/oPTgyuTuUNZX6CynwhyeVWYgZscbyns8fT77R+aJeU5qJi8qzGYtfeTdKMrHPcTdshrd1I/6mc4w/Jxrr5Glf2As2r+4bKrbIYdymJSiqLEg7DKzVgF5pi3ADdjHEr3V4W1enAeIaLnnvQy9U3j8s91549J94mVoNmLH3n8Oi0dNxr69DyAw39XvQ+XXCCw0rcd8slicOHbhIwVQrLQG75rjIDt7AM2lz3u3Os1q1uBko6fQk8DXsCAWVjatk0k1h5wv3XwAZ7ExlOUgWNmVfZiU9fMu0oh/AMRa2hKCf9utGwhaX8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
